/// Symbol catalog and resolution for libSystem imports.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum LibSym {
    // I/O
    Write,
    Writev,
    Read,
    Open,
    Close,
    Mkdir,
    Unlink,
    Rmdir,
    Lstat,
    Fcopyfile,
    Rename,
    // FTS (file tree traversal)
    FtsOpen,
    FtsRead,
    FtsClose,
    FtsSet,
    // argv / option parsing
    Getopt,
    // Process
    Exit,
    Abort,
    // Memory
    Malloc,
    Free,
    Calloc,
    Realloc,
    // stdio
    Puts,
    Printf,
    Fprintf,
    Vprintf,
    Fputs,
    Fflush,
    Sprintf,
    Snprintf,
    Vsnprintf,
    // string
    Strlen,
    Strcmp,
    Strncmp,
    Strcpy,
    Strncpy,
    Strcat,
    Strchr,
    Strdup,
    Strcasecmp,
    Strncasecmp,
    Strstr,
    Strtok,
    Strsep,
    Strrchr,
    // memory
    Memcpy,
    Memmove,
    Memset,
    Memcmp,
    Memchr,
    // conversions
    Atoi,
    Atol,
    Atoll,
    Strtol,
    Strtoul,
    Strtoll,
    Strtoull,
    Strtod,
    Atof,
    // char classification / conversion
    Isdigit,
    Isalpha,
    Isalnum,
    Isspace,
    Isupper,
    Islower,
    Ispunct,
    Toupper,
    Tolower,
    // sorting
    Qsort,
    Bsearch,
    Abs,
    Labs,
    // env
    Getenv,
    Setenv,
    Unsetenv,
    // I/O (misc)
    Perror,
    Putchar,
    Getchar,
    // dynamic linking
    Dlopen,
    Dlsym,
    Dlclose,
    Dlerror,
    // pthread Phase 5
    PthreadCreate,
    PthreadJoin,
    PthreadSelf,
    PthreadMutexInit,
    PthreadMutexLock,
    PthreadMutexUnlock,
    PthreadMutexTrylock,
    PthreadMutexDestroy,
    PthreadRwlockInit,
    PthreadRwlockRdlock,
    PthreadRwlockWrlock,
    PthreadRwlockUnlock,
    PthreadRwlockDestroy,
    PthreadCondInit,
    PthreadCondWait,
    PthreadCondTimedwait,
    PthreadCondSignal,
    PthreadCondBroadcast,
    PthreadCondDestroy,
    PthreadAttrInit,
    PthreadAttrSetdetachstate,
    PthreadAttrSetstacksize,
    PthreadAttrDestroy,
    PthreadOnce,
    PthreadCancel,
    PthreadTestcancel,
    PthreadKeyCreate,
    PthreadKeyDelete,
    PthreadGetspecific,
    PthreadSetspecific,
    // setjmp / longjmp
    Setjmp,
    Longjmp,
    // math — results go to x87 ST(0)
    Sin,
    Cos,
    Tan,
    Sqrt,
    Pow,
    Log,
    Log2,
    Log10,
    Exp,
    Exp2,
    Floor,
    Ceil,
    Round,
    Fabs,
    Fmod,
    Atan,
    Atan2,
    Asin,
    Acos,
    Sinh,
    Cosh,
    Tanh,
    Sinf,
    Cosf,
    Tanf,
    Sqrtf,
    Powf,
    Logf,
    Expf,
    Fabsf,
    Floorf,
    Ceilf,
    // ObjC runtime stubs
    ObjcMsgSend,
    ObjcMsgSendStret,
    ObjcGetClass,
    ObjcLookUpClass,
    NSLog,
    // Internal sentinels
    ThreadSentinel,
    SignalReturn,
    // Silent no-ops
    Stub0,
}

fn base_name(raw: &str) -> &str {
    let s = raw.trim_start_matches('_');
    if let Some(i) = s.find('$') {
        &s[..i]
    } else {
        s
    }
}

pub fn known_symbol(name: &str) -> Option<LibSym> {
    match base_name(name) {
        "write" | "write_nocancel" | "pwrite" => Some(LibSym::Write),
        "writev" | "writev_nocancel" => Some(LibSym::Writev),
        "read" | "read_nocancel" | "pread" => Some(LibSym::Read),
        "open" | "open_nocancel" => Some(LibSym::Open),
        "close" | "close_nocancel" => Some(LibSym::Close),
        "mkdir" => Some(LibSym::Mkdir),
        "unlink" | "unlink$UNIX2003" => Some(LibSym::Unlink),
        "rmdir" | "rmdir$UNIX2003" => Some(LibSym::Rmdir),
        "lstat" | "lstat$INODE64" | "lstat$UNIX2003" => Some(LibSym::Lstat),
        "fcopyfile" => Some(LibSym::Fcopyfile),
        "rename" => Some(LibSym::Rename),
        "fts_open" | "fts_open$INODE64" => Some(LibSym::FtsOpen),
        "fts_read" | "fts_read$INODE64" => Some(LibSym::FtsRead),
        "fts_close" | "fts_close$INODE64" => Some(LibSym::FtsClose),
        "fts_set" | "fts_set$INODE64" => Some(LibSym::FtsSet),
        "getopt" => Some(LibSym::Getopt),
        "exit" | "_exit" | "quick_exit" => Some(LibSym::Exit),
        "abort" => Some(LibSym::Abort),
        "malloc" | "malloc_zone_malloc" => Some(LibSym::Malloc),
        "free" | "malloc_zone_free" => Some(LibSym::Free),
        "calloc" | "malloc_zone_calloc" => Some(LibSym::Calloc),
        "realloc" | "malloc_zone_realloc" => Some(LibSym::Realloc),
        "puts" => Some(LibSym::Puts),
        "printf" | "__printf_chk" | "printf_chk" => Some(LibSym::Printf),
        "fprintf" | "__fprintf_chk" => Some(LibSym::Fprintf),
        "vprintf" | "__vprintf_chk" => Some(LibSym::Vprintf),
        "fputs" => Some(LibSym::Fputs),
        "fflush" => Some(LibSym::Fflush),
        "sprintf" | "__sprintf_chk" => Some(LibSym::Sprintf),
        "snprintf" | "__snprintf_chk" => Some(LibSym::Snprintf),
        "vsnprintf" | "__vsnprintf_chk" => Some(LibSym::Vsnprintf),
        "strlen" => Some(LibSym::Strlen),
        "strcmp" => Some(LibSym::Strcmp),
        "strncmp" => Some(LibSym::Strncmp),
        "strcpy" | "__strcpy_chk" => Some(LibSym::Strcpy),
        "strncpy" | "__strncpy_chk" => Some(LibSym::Strncpy),
        "strcat" | "__strcat_chk" => Some(LibSym::Strcat),
        "strchr" => Some(LibSym::Strchr),
        "strrchr" => Some(LibSym::Strrchr),
        "strdup" => Some(LibSym::Strdup),
        "strcasecmp" => Some(LibSym::Strcasecmp),
        "strncasecmp" => Some(LibSym::Strncasecmp),
        "strstr" => Some(LibSym::Strstr),
        "strtok" | "strtok_r" => Some(LibSym::Strtok),
        "strsep" => Some(LibSym::Strsep),
        "memcpy" | "__memcpy_chk" => Some(LibSym::Memcpy),
        "memmove" | "__memmove_chk" => Some(LibSym::Memmove),
        "memset" | "__memset_chk" => Some(LibSym::Memset),
        "memcmp" => Some(LibSym::Memcmp),
        "memchr" => Some(LibSym::Memchr),
        "atoi" => Some(LibSym::Atoi),
        "atol" => Some(LibSym::Atol),
        "atoll" => Some(LibSym::Atoll),
        "strtol" => Some(LibSym::Strtol),
        "strtoul" => Some(LibSym::Strtoul),
        "strtoll" => Some(LibSym::Strtoll),
        "strtoull" => Some(LibSym::Strtoull),
        "strtod" => Some(LibSym::Strtod),
        "atof" => Some(LibSym::Atof),
        "isdigit" | "isdigit_l" => Some(LibSym::Isdigit),
        "isalpha" | "isalpha_l" => Some(LibSym::Isalpha),
        "isalnum" | "isalnum_l" => Some(LibSym::Isalnum),
        "isspace" | "isspace_l" => Some(LibSym::Isspace),
        "isupper" | "isupper_l" => Some(LibSym::Isupper),
        "islower" | "islower_l" => Some(LibSym::Islower),
        "ispunct" | "ispunct_l" => Some(LibSym::Ispunct),
        "toupper" | "toupper_l" => Some(LibSym::Toupper),
        "tolower" | "tolower_l" => Some(LibSym::Tolower),
        "qsort" | "qsort_r" => Some(LibSym::Qsort),
        "bsearch" => Some(LibSym::Bsearch),
        "abs" => Some(LibSym::Abs),
        "labs" => Some(LibSym::Labs),
        "getenv" => Some(LibSym::Getenv),
        "setenv" => Some(LibSym::Setenv),
        "unsetenv" => Some(LibSym::Unsetenv),
        "perror" => Some(LibSym::Perror),
        "putchar" | "putchar_unlocked" => Some(LibSym::Putchar),
        "getchar" | "getchar_unlocked" => Some(LibSym::Getchar),
        "dlopen" => Some(LibSym::Dlopen),
        "dlsym" => Some(LibSym::Dlsym),
        "dlclose" => Some(LibSym::Dlclose),
        "dlerror" => Some(LibSym::Dlerror),
        // pthread
        "pthread_create" => Some(LibSym::PthreadCreate),
        "pthread_join" => Some(LibSym::PthreadJoin),
        "pthread_self" => Some(LibSym::PthreadSelf),
        "pthread_mutex_init" => Some(LibSym::PthreadMutexInit),
        "pthread_mutex_lock" => Some(LibSym::PthreadMutexLock),
        "pthread_mutex_unlock" => Some(LibSym::PthreadMutexUnlock),
        "pthread_mutex_trylock" => Some(LibSym::PthreadMutexTrylock),
        "pthread_mutex_destroy" => Some(LibSym::PthreadMutexDestroy),
        "pthread_rwlock_init" => Some(LibSym::PthreadRwlockInit),
        "pthread_rwlock_rdlock" => Some(LibSym::PthreadRwlockRdlock),
        "pthread_rwlock_wrlock" => Some(LibSym::PthreadRwlockWrlock),
        "pthread_rwlock_unlock" => Some(LibSym::PthreadRwlockUnlock),
        "pthread_rwlock_destroy" => Some(LibSym::PthreadRwlockDestroy),
        "pthread_cond_init" => Some(LibSym::PthreadCondInit),
        "pthread_cond_wait" => Some(LibSym::PthreadCondWait),
        "pthread_cond_timedwait" => Some(LibSym::PthreadCondTimedwait),
        "pthread_cond_signal" => Some(LibSym::PthreadCondSignal),
        "pthread_cond_broadcast" => Some(LibSym::PthreadCondBroadcast),
        "pthread_cond_destroy" => Some(LibSym::PthreadCondDestroy),
        "pthread_attr_init" => Some(LibSym::PthreadAttrInit),
        "pthread_attr_setdetachstate" => Some(LibSym::PthreadAttrSetdetachstate),
        "pthread_attr_setstacksize" => Some(LibSym::PthreadAttrSetstacksize),
        "pthread_attr_destroy" => Some(LibSym::PthreadAttrDestroy),
        "pthread_once" => Some(LibSym::PthreadOnce),
        "pthread_cancel" => Some(LibSym::PthreadCancel),
        "pthread_testcancel" => Some(LibSym::PthreadTestcancel),
        "pthread_key_create" => Some(LibSym::PthreadKeyCreate),
        "pthread_key_delete" => Some(LibSym::PthreadKeyDelete),
        "pthread_getspecific" => Some(LibSym::PthreadGetspecific),
        "pthread_setspecific" => Some(LibSym::PthreadSetspecific),
        // setjmp
        "setjmp" | "_setjmp" | "sigsetjmp" => Some(LibSym::Setjmp),
        "longjmp" | "_longjmp" | "siglongjmp" => Some(LibSym::Longjmp),
        // math (double)
        "sin" => Some(LibSym::Sin),
        "cos" => Some(LibSym::Cos),
        "tan" => Some(LibSym::Tan),
        "sqrt" => Some(LibSym::Sqrt),
        "pow" => Some(LibSym::Pow),
        "log" => Some(LibSym::Log),
        "log2" => Some(LibSym::Log2),
        "log10" => Some(LibSym::Log10),
        "exp" => Some(LibSym::Exp),
        "exp2" => Some(LibSym::Exp2),
        "floor" => Some(LibSym::Floor),
        "ceil" => Some(LibSym::Ceil),
        "round" => Some(LibSym::Round),
        "fabs" => Some(LibSym::Fabs),
        "fmod" => Some(LibSym::Fmod),
        "atan" => Some(LibSym::Atan),
        "atan2" => Some(LibSym::Atan2),
        "asin" => Some(LibSym::Asin),
        "acos" => Some(LibSym::Acos),
        "sinh" => Some(LibSym::Sinh),
        "cosh" => Some(LibSym::Cosh),
        "tanh" => Some(LibSym::Tanh),
        // math (float)
        "sinf" => Some(LibSym::Sinf),
        "cosf" => Some(LibSym::Cosf),
        "tanf" => Some(LibSym::Tanf),
        "sqrtf" => Some(LibSym::Sqrtf),
        "powf" => Some(LibSym::Powf),
        "logf" => Some(LibSym::Logf),
        "expf" => Some(LibSym::Expf),
        "fabsf" => Some(LibSym::Fabsf),
        "floorf" => Some(LibSym::Floorf),
        "ceilf" => Some(LibSym::Ceilf),
        // ObjC runtime
        "objc_msgSend" => Some(LibSym::ObjcMsgSend),
        "objc_msgSend_stret" => Some(LibSym::ObjcMsgSendStret),
        "objc_getClass" => Some(LibSym::ObjcGetClass),
        "objc_lookUpClass" => Some(LibSym::ObjcLookUpClass),
        "NSLog" => Some(LibSym::NSLog),
        // no-op stubs
        "atexit"
        | "__cxa_atexit"
        | "__cxa_finalize"
        | "__cxa_thread_atexit"
        | "setlocale"
        | "bindtextdomain"
        | "textdomain"
        | "tzset"
        | "__pthread_sigmask"
        | "pthread_sigmask"
        | "pthread_atfork"
        | "mach_init_routine"
        | "__dyld_func_lookup"
        | "dyld_stub_binding_helper"
        | "__keymgr_dwarf2_register_sections"
        | "_Block_object_assign"
        | "_Block_object_dispose" => Some(LibSym::Stub0),
        _ => None,
    }
}

pub fn known_data_symbol(name: &str) -> Option<u32> {
    match base_name(name) {
        "optind" => Some(0x5000_F000),
        "optarg" => Some(0x5000_F004),
        _ => None,
    }
}
