/// Symbol catalog and resolution for libSystem imports.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum LibSym {
    Error,
    // I/O
    Write,
    Writev,
    Read,
    Open,
    Close,
    Mkdir,
    Unlink,
    Rmdir,
    Fstat,
    Lstat,
    Stat,
    Fcopyfile,
    Copyfile,
    Rename,
    // permissions and ownership
    Chmod,
    Fchmod,
    Chown,
    Fchown,
    // FTS (file tree traversal)
    FtsOpen,
    FtsRead,
    FtsClose,
    FtsSet,
    FtsChildren,
    // argv / option parsing
    Getopt,
    // Process
    Exit,
    Abort,
    // Memory
    Malloc,
    Free,
    Calloc,
    Realloc,
    // stdio
    Puts,
    Printf,
    Fprintf,
    Vprintf,
    Fputs,
    Fflush,
    Sprintf,
    Snprintf,
    Vsnprintf,
    // string
    Strlen,
    Strcmp,
    Strncmp,
    Strcpy,
    Strncpy,
    Strcat,
    Strncat,
    Strlcpy,
    Strlcat,
    Strchr,
    Strdup,
    Strcasecmp,
    Strncasecmp,
    Strstr,
    Strtok,
    Strsep,
    Strrchr,
    // memory
    Memcpy,
    Memmove,
    Memset,
    Memcmp,
    Memchr,
    // conversions
    Atoi,
    Atol,
    Atoll,
    Strtol,
    Strtoul,
    Strtoll,
    Strtoull,
    Strtod,
    Atof,
    // char classification / conversion
    Isdigit,
    MaskRune,
    Isalpha,
    Isalnum,
    Isspace,
    Isupper,
    Islower,
    Ispunct,
    Toupper,
    Tolower,
    // sorting
    Qsort,
    Bsearch,
    Abs,
    Labs,
    // env
    Getenv,
    Setenv,
    Unsetenv,
    // I/O (misc)
    Perror,
    Putchar,
    Getchar,
    // wide-char / multibyte
    Mbrtowc,
    Wcwidth,
    // stdio FILE* operations
    Fileno,
    Fdopen,
    Fwrite,
    Fclose,
    Feof,
    Ferror,
    Clearerr,
    // dynamic linking
    Dlopen,
    Dlsym,
    Dlclose,
    Dlerror,
    // pthread Phase 5
    PthreadCreate,
    PthreadJoin,
    PthreadSelf,
    PthreadMutexInit,
    PthreadMutexLock,
    PthreadMutexUnlock,
    PthreadMutexTrylock,
    PthreadMutexDestroy,
    PthreadRwlockInit,
    PthreadRwlockRdlock,
    PthreadRwlockWrlock,
    PthreadRwlockUnlock,
    PthreadRwlockDestroy,
    PthreadCondInit,
    PthreadCondWait,
    PthreadCondTimedwait,
    PthreadCondSignal,
    PthreadCondBroadcast,
    PthreadCondDestroy,
    PthreadAttrInit,
    PthreadAttrSetdetachstate,
    PthreadAttrSetstacksize,
    PthreadAttrDestroy,
    PthreadOnce,
    PthreadCancel,
    PthreadTestcancel,
    PthreadKeyCreate,
    PthreadKeyDelete,
    PthreadGetspecific,
    PthreadSetspecific,
    // setjmp / longjmp
    Setjmp,
    Longjmp,
    // math — results go to x87 ST(0)
    Sin,
    Cos,
    Tan,
    Sqrt,
    Pow,
    Log,
    Log2,
    Log10,
    Exp,
    Exp2,
    Floor,
    Ceil,
    Round,
    Fabs,
    Fmod,
    Atan,
    Atan2,
    Asin,
    Acos,
    Sinh,
    Cosh,
    Tanh,
    Sinf,
    Cosf,
    Tanf,
    Sqrtf,
    Powf,
    Logf,
    Expf,
    Fabsf,
    Floorf,
    Ceilf,
    // ObjC runtime stubs
    ObjcMsgSend,
    ObjcMsgSendStret,
    ObjcGetClass,
    ObjcLookUpClass,
    NSLog,
    // Internal sentinels
    ThreadSentinel,
    SignalReturn,
    CfApplySentinel,
    // Sleep
    Sleep,
    Nanosleep,
    // CoreFoundation
    CFAbsoluteTimeGetCurrent,
    CFArrayAppendArray,
    CFArrayAppendValue,
    CFArrayApplyFunction,
    CFArrayContainsValue,
    CFArrayCreateCopy,
    CFArrayCreateMutable,
    CFArrayCreateMutableCopy,
    CFArrayGetCount,
    CFArrayGetTypeID,
    CFArrayGetValueAtIndex,
    CFArrayInsertValueAtIndex,
    CFArrayRemoveAllValues,
    CFArrayRemoveValueAtIndex,
    CFArraySortValues,
    CFBagApplyFunction,
    CFBagGetTypeID,
    CFBooleanGetTypeID,
    CFBooleanGetValue,
    CFBundleCopyBundleURL,
    CFBundleCopyLocalizedString,
    CFBundleCopyResourceURL,
    CFBundleCopyResourcesDirectoryURL,
    CFBundleCreate,
    CFBundleCreateBundlesFromDirectory,
    CFBundleGetBundleWithIdentifier,
    CFBundleGetInfoDictionary,
    CFDataAppendBytes,
    CFDataCreate,
    CFDataCreateMutable,
    CFDataCreateWithBytesNoCopy,
    CFDataGetBytePtr,
    CFDataGetBytes,
    CFDataGetLength,
    CFDataGetMutableBytePtr,
    CFDataGetTypeID,
    CFDataSetLength,
    CFDictionaryAddValue,
    CFDictionaryApplyFunction,
    CFDictionaryContainsKey,
    CFDictionaryCreateMutable,
    CFDictionaryCreateMutableCopy,
    CFDictionaryGetCount,
    CFDictionaryGetKeysAndValues,
    CFDictionaryGetTypeID,
    CFDictionaryGetValue,
    CFDictionaryGetValueIfPresent,
    CFDictionaryRemoveValue,
    CFDictionaryReplaceValue,
    CFDictionarySetValue,
    CFEqual,
    CFGetTypeID,
    CFNumberCreate,
    CFNumberGetTypeID,
    CFNumberGetValue,
    CFPropertyListCreateFromStream,
    CFPropertyListCreateFromXMLData,
    CFPropertyListCreateXMLData,
    CFReadStreamClose,
    CFReadStreamCreateWithBytesNoCopy,
    CFReadStreamOpen,
    CFRelease,
    CFRetain,
    CFRunLoopAddSource,
    CFRunLoopAddTimer,
    CFRunLoopGetCurrent,
    CFRunLoopRemoveTimer,
    CFRunLoopRun,
    CFRunLoopRunInMode,
    CFRunLoopSourceInvalidate,
    CFRunLoopStop,
    CFRunLoopTimerCreate,
    CFSetApplyFunction,
    CFSetGetTypeID,
    CFShow,
    CFStringAppend,
    CFStringCompare,
    CFStringCompareWithOptions,
    CFStringCreateArrayBySeparatingStrings,
    CFStringCreateCopy,
    CFStringCreateExternalRepresentation,
    CFStringCreateFromExternalRepresentation,
    CFStringCreateMutable,
    CFStringCreateMutableCopy,
    CFStringCreateWithCString,
    CFStringCreateWithCharacters,
    CFStringCreateWithFileSystemRepresentation,
    CFStringCreateWithFormat,
    CFStringCreateWithSubstring,
    CFStringDelete,
    CFStringFind,
    CFStringGetBytes,
    CFStringGetCString,
    CFStringGetCharacters,
    CFStringGetFileSystemRepresentation,
    CFStringGetLength,
    CFStringGetMaximumSizeForEncoding,
    CFStringGetMaximumSizeOfFileSystemRepresentation,
    CFStringGetPascalString,
    CFStringGetTypeID,
    CFStringHasPrefix,
    CFStringHasSuffix,
    CFStringTrimWhitespace,
    CFTreeApplyFunctionToChildren,
    CFTreeGetChildCount,
    CFTreeGetContext,
    CFTreeGetNextSibling,
    CFTreeGetTypeID,
    CFURLCopyAbsoluteURL,
    CFURLCopyFileSystemPath,
    CFURLCopyLastPathComponent,
    CFURLCopyPathExtension,
    CFURLCopyScheme,
    CFURLCreateCopyAppendingPathComponent,
    CFURLCreateCopyAppendingPathExtension,
    CFURLCreateCopyDeletingLastPathComponent,
    CFURLCreateDataAndPropertiesFromResource,
    CFURLCreateFromFSRef,
    CFURLCreateFromFileSystemRepresentation,
    CFURLCreatePropertyFromResource,
    CFURLCreateWithBytes,
    CFURLCreateWithFileSystemPath,
    CFURLCreateWithFileSystemPathRelativeToBase,
    CFURLCreateWithString,
    CFURLGetFileSystemRepresentation,
    CFURLGetString,
    CFURLHasDirectoryPath,
    CFUUIDCreate,
    CFUUIDGetUUIDBytes,
    // Silent no-ops
    Stub0,
}

fn base_name(raw: &str) -> &str {
    let s = raw.trim_start_matches('_');
    if let Some(i) = s.find('$') {
        &s[..i]
    } else {
        s
    }
}

pub fn known_symbol(name: &str) -> Option<LibSym> {
    match base_name(name) {
        "error" => Some(LibSym::Error),
        "write" | "write_nocancel" | "pwrite" => Some(LibSym::Write),
        "writev" | "writev_nocancel" => Some(LibSym::Writev),
        "read" | "read_nocancel" | "pread" => Some(LibSym::Read),
        "open" | "open_nocancel" => Some(LibSym::Open),
        "close" | "close_nocancel" => Some(LibSym::Close),
        "mkdir" => Some(LibSym::Mkdir),
        "unlink" => Some(LibSym::Unlink),
        "rmdir" => Some(LibSym::Rmdir),
        "fstat" => Some(LibSym::Fstat),
        "lstat" => Some(LibSym::Lstat),
        "stat" => Some(LibSym::Stat),
        "fcopyfile" => Some(LibSym::Fcopyfile),
        "copyfile" => Some(LibSym::Copyfile),
        "rename" => Some(LibSym::Rename),
        "chmod" => Some(LibSym::Chmod),
        "fchmod" => Some(LibSym::Fchmod),
        "chown" => Some(LibSym::Chown),
        "fchown" => Some(LibSym::Fchown),
        "fts_open" => Some(LibSym::FtsOpen),
        "fts_read" => Some(LibSym::FtsRead),
        "fts_close" => Some(LibSym::FtsClose),
        "fts_set" => Some(LibSym::FtsSet),
        "fts_children" => Some(LibSym::FtsChildren),
        "getopt" => Some(LibSym::Getopt),
        "exit" | "_exit" | "quick_exit" => Some(LibSym::Exit),
        "abort" => Some(LibSym::Abort),
        "malloc" | "malloc_zone_malloc" => Some(LibSym::Malloc),
        "free" | "malloc_zone_free" => Some(LibSym::Free),
        "calloc" | "malloc_zone_calloc" => Some(LibSym::Calloc),
        "realloc" | "malloc_zone_realloc" => Some(LibSym::Realloc),
        "puts" => Some(LibSym::Puts),
        "printf" | "__printf_chk" | "printf_chk" => Some(LibSym::Printf),
        "fprintf" | "__fprintf_chk" => Some(LibSym::Fprintf),
        "vprintf" | "__vprintf_chk" => Some(LibSym::Vprintf),
        "fputs" => Some(LibSym::Fputs),
        "fflush" => Some(LibSym::Fflush),
        "sprintf" | "__sprintf_chk" => Some(LibSym::Sprintf),
        "snprintf" | "__snprintf_chk" => Some(LibSym::Snprintf),
        "vsnprintf" | "__vsnprintf_chk" => Some(LibSym::Vsnprintf),
        "strlen" => Some(LibSym::Strlen),
        "strcmp" => Some(LibSym::Strcmp),
        "strncmp" => Some(LibSym::Strncmp),
        "strcpy" | "__strcpy_chk" => Some(LibSym::Strcpy),
        "strncpy" | "__strncpy_chk" => Some(LibSym::Strncpy),
        "strcat" | "__strcat_chk" => Some(LibSym::Strcat),
        "strncat" | "__strncat_chk" => Some(LibSym::Strncat),
        "strlcpy" => Some(LibSym::Strlcpy),
        "strlcat" => Some(LibSym::Strlcat),
        "strchr" => Some(LibSym::Strchr),
        "strrchr" => Some(LibSym::Strrchr),
        "strdup" => Some(LibSym::Strdup),
        "strcasecmp" => Some(LibSym::Strcasecmp),
        "strncasecmp" => Some(LibSym::Strncasecmp),
        "strstr" => Some(LibSym::Strstr),
        "strtok" | "strtok_r" => Some(LibSym::Strtok),
        "strsep" => Some(LibSym::Strsep),
        "memcpy" | "__memcpy_chk" => Some(LibSym::Memcpy),
        "memmove" | "__memmove_chk" => Some(LibSym::Memmove),
        "memset" | "__memset_chk" => Some(LibSym::Memset),
        "memcmp" => Some(LibSym::Memcmp),
        "memchr" => Some(LibSym::Memchr),
        "atoi" => Some(LibSym::Atoi),
        "atol" => Some(LibSym::Atol),
        "atoll" => Some(LibSym::Atoll),
        "strtol" => Some(LibSym::Strtol),
        "strtoul" => Some(LibSym::Strtoul),
        "strtoll" => Some(LibSym::Strtoll),
        "strtoull" => Some(LibSym::Strtoull),
        "strtod" => Some(LibSym::Strtod),
        "atof" => Some(LibSym::Atof),
        "isdigit" | "isdigit_l" => Some(LibSym::Isdigit),
        "maskrune" => Some(LibSym::MaskRune),
        "isalpha" | "isalpha_l" => Some(LibSym::Isalpha),
        "isalnum" | "isalnum_l" => Some(LibSym::Isalnum),
        "isspace" | "isspace_l" => Some(LibSym::Isspace),
        "isupper" | "isupper_l" => Some(LibSym::Isupper),
        "islower" | "islower_l" => Some(LibSym::Islower),
        "ispunct" | "ispunct_l" => Some(LibSym::Ispunct),
        "toupper" | "toupper_l" => Some(LibSym::Toupper),
        "tolower" | "tolower_l" => Some(LibSym::Tolower),
        "qsort" | "qsort_r" => Some(LibSym::Qsort),
        "bsearch" => Some(LibSym::Bsearch),
        "abs" => Some(LibSym::Abs),
        "labs" => Some(LibSym::Labs),
        "getenv" => Some(LibSym::Getenv),
        "setenv" => Some(LibSym::Setenv),
        "unsetenv" => Some(LibSym::Unsetenv),
        "perror" => Some(LibSym::Perror),
        "putchar" | "putchar_unlocked" => Some(LibSym::Putchar),
        "getchar" | "getchar_unlocked" => Some(LibSym::Getchar),
        "mbrtowc" => Some(LibSym::Mbrtowc),
        "wcwidth" => Some(LibSym::Wcwidth),
        "fileno" | "fileno_unlocked" => Some(LibSym::Fileno),
        "fdopen" => Some(LibSym::Fdopen),
        "fwrite" => Some(LibSym::Fwrite),
        "fclose" => Some(LibSym::Fclose),
        "feof" | "feof_unlocked" => Some(LibSym::Feof),
        "ferror" | "ferror_unlocked" => Some(LibSym::Ferror),
        "clearerr" | "clearerr_unlocked" => Some(LibSym::Clearerr),
        "dlopen" => Some(LibSym::Dlopen),
        "dlsym" => Some(LibSym::Dlsym),
        "dlclose" => Some(LibSym::Dlclose),
        "dlerror" => Some(LibSym::Dlerror),
        // pthread
        "pthread_create" => Some(LibSym::PthreadCreate),
        "pthread_join" => Some(LibSym::PthreadJoin),
        "pthread_self" => Some(LibSym::PthreadSelf),
        "pthread_mutex_init" => Some(LibSym::PthreadMutexInit),
        "pthread_mutex_lock" => Some(LibSym::PthreadMutexLock),
        "pthread_mutex_unlock" => Some(LibSym::PthreadMutexUnlock),
        "pthread_mutex_trylock" => Some(LibSym::PthreadMutexTrylock),
        "pthread_mutex_destroy" => Some(LibSym::PthreadMutexDestroy),
        "pthread_rwlock_init" => Some(LibSym::PthreadRwlockInit),
        "pthread_rwlock_rdlock" => Some(LibSym::PthreadRwlockRdlock),
        "pthread_rwlock_wrlock" => Some(LibSym::PthreadRwlockWrlock),
        "pthread_rwlock_unlock" => Some(LibSym::PthreadRwlockUnlock),
        "pthread_rwlock_destroy" => Some(LibSym::PthreadRwlockDestroy),
        "pthread_cond_init" => Some(LibSym::PthreadCondInit),
        "pthread_cond_wait" => Some(LibSym::PthreadCondWait),
        "pthread_cond_timedwait" => Some(LibSym::PthreadCondTimedwait),
        "pthread_cond_signal" => Some(LibSym::PthreadCondSignal),
        "pthread_cond_broadcast" => Some(LibSym::PthreadCondBroadcast),
        "pthread_cond_destroy" => Some(LibSym::PthreadCondDestroy),
        "pthread_attr_init" => Some(LibSym::PthreadAttrInit),
        "pthread_attr_setdetachstate" => Some(LibSym::PthreadAttrSetdetachstate),
        "pthread_attr_setstacksize" => Some(LibSym::PthreadAttrSetstacksize),
        "pthread_attr_destroy" => Some(LibSym::PthreadAttrDestroy),
        "pthread_once" => Some(LibSym::PthreadOnce),
        "pthread_cancel" => Some(LibSym::PthreadCancel),
        "pthread_testcancel" => Some(LibSym::PthreadTestcancel),
        "pthread_key_create" => Some(LibSym::PthreadKeyCreate),
        "pthread_key_delete" => Some(LibSym::PthreadKeyDelete),
        "pthread_getspecific" => Some(LibSym::PthreadGetspecific),
        "pthread_setspecific" => Some(LibSym::PthreadSetspecific),
        // setjmp
        "setjmp" | "_setjmp" | "sigsetjmp" => Some(LibSym::Setjmp),
        "longjmp" | "_longjmp" | "siglongjmp" => Some(LibSym::Longjmp),
        // math (double)
        "sin" => Some(LibSym::Sin),
        "cos" => Some(LibSym::Cos),
        "tan" => Some(LibSym::Tan),
        "sqrt" => Some(LibSym::Sqrt),
        "pow" => Some(LibSym::Pow),
        "log" => Some(LibSym::Log),
        "log2" => Some(LibSym::Log2),
        "log10" => Some(LibSym::Log10),
        "exp" => Some(LibSym::Exp),
        "exp2" => Some(LibSym::Exp2),
        "floor" => Some(LibSym::Floor),
        "ceil" => Some(LibSym::Ceil),
        "round" => Some(LibSym::Round),
        "fabs" => Some(LibSym::Fabs),
        "fmod" => Some(LibSym::Fmod),
        "atan" => Some(LibSym::Atan),
        "atan2" => Some(LibSym::Atan2),
        "asin" => Some(LibSym::Asin),
        "acos" => Some(LibSym::Acos),
        "sinh" => Some(LibSym::Sinh),
        "cosh" => Some(LibSym::Cosh),
        "tanh" => Some(LibSym::Tanh),
        // math (float)
        "sinf" => Some(LibSym::Sinf),
        "cosf" => Some(LibSym::Cosf),
        "tanf" => Some(LibSym::Tanf),
        "sqrtf" => Some(LibSym::Sqrtf),
        "powf" => Some(LibSym::Powf),
        "logf" => Some(LibSym::Logf),
        "expf" => Some(LibSym::Expf),
        "fabsf" => Some(LibSym::Fabsf),
        "floorf" => Some(LibSym::Floorf),
        "ceilf" => Some(LibSym::Ceilf),
        // ObjC runtime
        "objc_msgSend" => Some(LibSym::ObjcMsgSend),
        "objc_msgSend_stret" => Some(LibSym::ObjcMsgSendStret),
        "objc_getClass" => Some(LibSym::ObjcGetClass),
        "objc_lookUpClass" => Some(LibSym::ObjcLookUpClass),
        "NSLog" => Some(LibSym::NSLog),
        // Sleep
        "sleep" => Some(LibSym::Sleep),
        "nanosleep" => Some(LibSym::Nanosleep),
        // Core Foundation
        "CFAbsoluteTimeGetCurrent" => Some(LibSym::CFAbsoluteTimeGetCurrent),
        "CFArrayAppendArray" => Some(LibSym::CFArrayAppendArray),
        "CFArrayAppendValue" => Some(LibSym::CFArrayAppendValue),
        "CFArrayApplyFunction" => Some(LibSym::CFArrayApplyFunction),
        "CFArrayContainsValue" => Some(LibSym::CFArrayContainsValue),
        "CFArrayCreateCopy" => Some(LibSym::CFArrayCreateCopy),
        "CFArrayCreateMutable" => Some(LibSym::CFArrayCreateMutable),
        "CFArrayCreateMutableCopy" => Some(LibSym::CFArrayCreateMutableCopy),
        "CFArrayGetCount" => Some(LibSym::CFArrayGetCount),
        "CFArrayGetTypeID" => Some(LibSym::CFArrayGetTypeID),
        "CFArrayGetValueAtIndex" => Some(LibSym::CFArrayGetValueAtIndex),
        "CFArrayInsertValueAtIndex" => Some(LibSym::CFArrayInsertValueAtIndex),
        "CFArrayRemoveAllValues" => Some(LibSym::CFArrayRemoveAllValues),
        "CFArrayRemoveValueAtIndex" => Some(LibSym::CFArrayRemoveValueAtIndex),
        "CFArraySortValues" => Some(LibSym::CFArraySortValues),

        "CFBagApplyFunction" => Some(LibSym::CFBagApplyFunction),
        "CFBagGetTypeID" => Some(LibSym::CFBagGetTypeID),
        "CFBooleanGetTypeID" => Some(LibSym::CFBooleanGetTypeID),
        "CFBooleanGetValue" => Some(LibSym::CFBooleanGetValue),
        "CFBundleCopyBundleURL" => Some(LibSym::CFBundleCopyBundleURL),
        "CFBundleCopyLocalizedString" => Some(LibSym::CFBundleCopyLocalizedString),
        "CFBundleCopyResourceURL" => Some(LibSym::CFBundleCopyResourceURL),
        "CFBundleCopyResourcesDirectoryURL" => Some(LibSym::CFBundleCopyResourcesDirectoryURL),
        "CFBundleCreate" => Some(LibSym::CFBundleCreate),
        "CFBundleCreateBundlesFromDirectory" => Some(LibSym::CFBundleCreateBundlesFromDirectory),
        "CFBundleGetBundleWithIdentifier" => Some(LibSym::CFBundleGetBundleWithIdentifier),
        "CFBundleGetInfoDictionary" => Some(LibSym::CFBundleGetInfoDictionary),
        "CFDataAppendBytes" => Some(LibSym::CFDataAppendBytes),
        "CFDataCreate" => Some(LibSym::CFDataCreate),
        "CFDataCreateMutable" => Some(LibSym::CFDataCreateMutable),
        "CFDataCreateWithBytesNoCopy" => Some(LibSym::CFDataCreateWithBytesNoCopy),
        "CFDataGetBytePtr" => Some(LibSym::CFDataGetBytePtr),
        "CFDataGetBytes" => Some(LibSym::CFDataGetBytes),
        "CFDataGetLength" => Some(LibSym::CFDataGetLength),
        "CFDataGetMutableBytePtr" => Some(LibSym::CFDataGetMutableBytePtr),
        "CFDataGetTypeID" => Some(LibSym::CFDataGetTypeID),
        "CFDataSetLength" => Some(LibSym::CFDataSetLength),
        "CFDictionaryAddValue" => Some(LibSym::CFDictionaryAddValue),
        "CFDictionaryApplyFunction" => Some(LibSym::CFDictionaryApplyFunction),
        "CFDictionaryContainsKey" => Some(LibSym::CFDictionaryContainsKey),
        "CFDictionaryCreateMutable" => Some(LibSym::CFDictionaryCreateMutable),
        "CFDictionaryCreateMutableCopy" => Some(LibSym::CFDictionaryCreateMutableCopy),
        "CFDictionaryGetCount" => Some(LibSym::CFDictionaryGetCount),
        "CFDictionaryGetKeysAndValues" => Some(LibSym::CFDictionaryGetKeysAndValues),
        "CFDictionaryGetTypeID" => Some(LibSym::CFDictionaryGetTypeID),
        "CFDictionaryGetValue" => Some(LibSym::CFDictionaryGetValue),
        "CFDictionaryGetValueIfPresent" => Some(LibSym::CFDictionaryGetValueIfPresent),
        "CFDictionaryRemoveValue" => Some(LibSym::CFDictionaryRemoveValue),
        "CFDictionaryReplaceValue" => Some(LibSym::CFDictionaryReplaceValue),
        "CFDictionarySetValue" => Some(LibSym::CFDictionarySetValue),
        "CFEqual" => Some(LibSym::CFEqual),
        "CFGetTypeID" => Some(LibSym::CFGetTypeID),
        "CFNumberCreate" => Some(LibSym::CFNumberCreate),
        "CFNumberGetTypeID" => Some(LibSym::CFNumberGetTypeID),
        "CFNumberGetValue" => Some(LibSym::CFNumberGetValue),
        "CFPropertyListCreateFromStream" => Some(LibSym::CFPropertyListCreateFromStream),
        "CFPropertyListCreateFromXMLData" => Some(LibSym::CFPropertyListCreateFromXMLData),
        "CFPropertyListCreateXMLData" => Some(LibSym::CFPropertyListCreateXMLData),
        "CFReadStreamClose" => Some(LibSym::CFReadStreamClose),
        "CFReadStreamCreateWithBytesNoCopy" => Some(LibSym::CFReadStreamCreateWithBytesNoCopy),
        "CFReadStreamOpen" => Some(LibSym::CFReadStreamOpen),
        "CFRelease" => Some(LibSym::CFRelease),
        "CFRetain" => Some(LibSym::CFRetain),
        "CFRunLoopAddSource" => Some(LibSym::CFRunLoopAddSource),
        "CFRunLoopAddTimer" => Some(LibSym::CFRunLoopAddTimer),
        "CFRunLoopGetCurrent" => Some(LibSym::CFRunLoopGetCurrent),
        "CFRunLoopRemoveTimer" => Some(LibSym::CFRunLoopRemoveTimer),
        "CFRunLoopRun" => Some(LibSym::CFRunLoopRun),
        "CFRunLoopRunInMode" => Some(LibSym::CFRunLoopRunInMode),
        "CFRunLoopSourceInvalidate" => Some(LibSym::CFRunLoopSourceInvalidate),
        "CFRunLoopStop" => Some(LibSym::CFRunLoopStop),
        "CFRunLoopTimerCreate" => Some(LibSym::CFRunLoopTimerCreate),
        "CFSetApplyFunction" => Some(LibSym::CFSetApplyFunction),
        "CFSetGetTypeID" => Some(LibSym::CFSetGetTypeID),
        "CFShow" => Some(LibSym::CFShow),
        "CFStringAppend" => Some(LibSym::CFStringAppend),
        "CFStringCompare" => Some(LibSym::CFStringCompare),
        "CFStringCompareWithOptions" => Some(LibSym::CFStringCompareWithOptions),
        "CFStringCreateArrayBySeparatingStrings" => {
            Some(LibSym::CFStringCreateArrayBySeparatingStrings)
        }
        "CFStringCreateCopy" => Some(LibSym::CFStringCreateCopy),
        "CFStringCreateExternalRepresentation" => {
            Some(LibSym::CFStringCreateExternalRepresentation)
        }
        "CFStringCreateFromExternalRepresentation" => {
            Some(LibSym::CFStringCreateFromExternalRepresentation)
        }
        "CFStringCreateMutable" => Some(LibSym::CFStringCreateMutable),
        "CFStringCreateMutableCopy" => Some(LibSym::CFStringCreateMutableCopy),
        "CFStringCreateWithCString" => Some(LibSym::CFStringCreateWithCString),
        "CFStringCreateWithCharacters" => Some(LibSym::CFStringCreateWithCharacters),
        "CFStringCreateWithFileSystemRepresentation" => {
            Some(LibSym::CFStringCreateWithFileSystemRepresentation)
        }
        "CFStringCreateWithFormat" => Some(LibSym::CFStringCreateWithFormat),
        "CFStringCreateWithSubstring" => Some(LibSym::CFStringCreateWithSubstring),
        "CFStringDelete" => Some(LibSym::CFStringDelete),
        "CFStringFind" => Some(LibSym::CFStringFind),
        "CFStringGetBytes" => Some(LibSym::CFStringGetBytes),
        "CFStringGetCString" => Some(LibSym::CFStringGetCString),
        "CFStringGetCharacters" => Some(LibSym::CFStringGetCharacters),
        "CFStringGetFileSystemRepresentation" => Some(LibSym::CFStringGetFileSystemRepresentation),
        "CFStringGetLength" => Some(LibSym::CFStringGetLength),
        "CFStringGetMaximumSizeForEncoding" => Some(LibSym::CFStringGetMaximumSizeForEncoding),
        "CFStringGetMaximumSizeOfFileSystemRepresentation" => {
            Some(LibSym::CFStringGetMaximumSizeOfFileSystemRepresentation)
        }
        "CFStringGetPascalString" => Some(LibSym::CFStringGetPascalString),
        "CFStringGetTypeID" => Some(LibSym::CFStringGetTypeID),
        "CFStringHasPrefix" => Some(LibSym::CFStringHasPrefix),
        "CFStringHasSuffix" => Some(LibSym::CFStringHasSuffix),
        "CFStringTrimWhitespace" => Some(LibSym::CFStringTrimWhitespace),
        "CFTreeApplyFunctionToChildren" => Some(LibSym::CFTreeApplyFunctionToChildren),
        "CFTreeGetChildCount" => Some(LibSym::CFTreeGetChildCount),
        "CFTreeGetContext" => Some(LibSym::CFTreeGetContext),
        "CFTreeGetNextSibling" => Some(LibSym::CFTreeGetNextSibling),
        "CFTreeGetTypeID" => Some(LibSym::CFTreeGetTypeID),
        "CFURLCopyAbsoluteURL" => Some(LibSym::CFURLCopyAbsoluteURL),
        "CFURLCopyFileSystemPath" => Some(LibSym::CFURLCopyFileSystemPath),
        "CFURLCopyLastPathComponent" => Some(LibSym::CFURLCopyLastPathComponent),
        "CFURLCopyPathExtension" => Some(LibSym::CFURLCopyPathExtension),
        "CFURLCopyScheme" => Some(LibSym::CFURLCopyScheme),
        "CFURLCreateCopyAppendingPathComponent" => {
            Some(LibSym::CFURLCreateCopyAppendingPathComponent)
        }
        "CFURLCreateCopyAppendingPathExtension" => {
            Some(LibSym::CFURLCreateCopyAppendingPathExtension)
        }
        "CFURLCreateCopyDeletingLastPathComponent" => {
            Some(LibSym::CFURLCreateCopyDeletingLastPathComponent)
        }
        "CFURLCreateDataAndPropertiesFromResource" => {
            Some(LibSym::CFURLCreateDataAndPropertiesFromResource)
        }
        "CFURLCreateFromFSRef" => Some(LibSym::CFURLCreateFromFSRef),
        "CFURLCreateFromFileSystemRepresentation" => {
            Some(LibSym::CFURLCreateFromFileSystemRepresentation)
        }
        "CFURLCreatePropertyFromResource" => Some(LibSym::CFURLCreatePropertyFromResource),
        "CFURLCreateWithBytes" => Some(LibSym::CFURLCreateWithBytes),
        "CFURLCreateWithFileSystemPath" => Some(LibSym::CFURLCreateWithFileSystemPath),
        "CFURLCreateWithFileSystemPathRelativeToBase" => {
            Some(LibSym::CFURLCreateWithFileSystemPathRelativeToBase)
        }
        "CFURLCreateWithString" => Some(LibSym::CFURLCreateWithString),
        "CFURLGetFileSystemRepresentation" => Some(LibSym::CFURLGetFileSystemRepresentation),
        "CFURLGetString" => Some(LibSym::CFURLGetString),
        "CFURLHasDirectoryPath" => Some(LibSym::CFURLHasDirectoryPath),
        "CFUUIDCreate" => Some(LibSym::CFUUIDCreate),
        "CFUUIDGetUUIDBytes" => Some(LibSym::CFUUIDGetUUIDBytes),
        // no-op stubs
        "atexit"
        | "__cxa_atexit"
        | "__cxa_finalize"
        | "__cxa_thread_atexit"
        | "setlocale"
        | "bindtextdomain"
        | "textdomain"
        | "tzset"
        | "__pthread_sigmask"
        | "pthread_sigmask"
        | "pthread_atfork"
        | "mach_init_routine"
        | "__dyld_func_lookup"
        | "dyld_stub_binding_helper"
        | "__keymgr_dwarf2_register_sections"
        | "_Block_object_assign"
        | "_Block_object_dispose" => Some(LibSym::Stub0),
        _ => None,
    }
}

pub fn known_data_symbol(name: &str) -> Option<u32> {
    match base_name(name) {
        "optind" => Some(0x5000_F000),
        "optarg" => Some(0x5000_F004),
        "___stack_chk_guard" | "__stack_chk_guard" | "stack_chk_guard" => Some(0x5003_0000),
        "__DefaultRuneLocale" | "DefaultRuneLocale" => Some(0x5003_1000),
        // stdio FILE* globals — slots point to storage holding the fake FILE* value.
        // base_name strips ALL leading underscores, so ___stdoutp → "stdoutp".
        "stdinp" => Some(0x5001_F000),
        "stdoutp" => Some(0x5001_F004),
        "stderrp" => Some(0x5001_F008),
        _ => None,
    }
}
